### ISSUE TITLE
영문 -> 한글 기능은 언제쯤 업데이트 예정인가요...

### ISSUE THREAD

**Issue by etgkqo** [jpoh281/flutter_korea_regexp#1]
영문 -> 한글 기능은 언제쯤 업데이트 되나요... 
타입스크립트 까막눈인 저에게 단비를 내려주세요

**Comment by jpoh281** [comment]
요즘 회사일로 정신이 없어서 바빠 확인을 늦게 했네요.
영어 한글 기능부터 구현하도록 노력해보겠습니다.

**Comment by jpoh281** [comment]
늦어서 죄송합니다 ㅠㅠ
@viiviii 님의 PR 덕분에 드디어 영문 -> 한글 기능 업데이트 했습니다.

현재 영문 -> 한글 기능을 구현하는 중에 몇가지 고민사항이 있긴하지만.. 일단 사용하실 수 있어요!
혹시나 어떤 방향으로 사용하실지 알려주시면 패키지 업데이트 방향에 도움이 될 듯 합니다.

이슈는 닫겠습니다. 혹시나 영문 -> 한글 기능에서 문제가 생기면 다시 생성해주세요!
