### ISSUE TITLE
자소 합치기 기능인 implode()의 파라미터 타입 종류

### ISSUE THREAD

**Issue by viiviii** [jpoh281/flutter_korea_regexp#2]
안녕하세요. 👑@jpoh281 👑님!
자소합치기와 영타->한타 변환 기능을 PR 드리려 하는데 고민되는 부분이 있어 의견을 구해봅니다!😁

### 주제
[원본 코드](https://github.com/bluewings/korean-regexp/blob/d963f9f97f85b5af95fa3ca40dbbac5d5677b250/src/implode.ts#L22)에서는 자바스크립트 union type 지원으로
`implode()` 함수가  `String`, `List<String>`, `List<List<String>` type을 모두 받아 처리하는데,
Dart에서는 union type이나 Java의 method overriding이 없어서 다른 방법이 필요할 것 같아요!

### 고민해본 방법
1) dynamic type으로 만들고 assert문으로 체크
```dart
String implode(dynamic input) {
  assert(input is String || input is List<String> || input is List<List<String>>);
  // ok
}
```

2) String type으로 만들고, 추후 다른 타입도 필요한 경우 메서드를 추가 생성
```dart
String implode(String input) {
}

String implodeList(List<String> inputs) {
}
```

제 생각은 나중에 변경이 필요한 경우 `String -> dynamic`으로 바꾸는건 간단하지만,
`dynamic -> String`은 호환성이 깨지므로 방법(2)가 좋아보여요.
하지만 방법(2)를 선택 시 추가 메서드가 생길 경우 원본과 사용 방법이 달라지는 부분이 마음에 걸립니다😭

다양한 의견 주시면 감사하겠습니다🙏🙏

**Comment by jpoh281** [comment]
1번 방식에서
early return하는건 어떻게 생각하세요?
해당 메소드가 String을 반환하는 함수이다보니 원하는 타입이 아닐 때 empty string을 반환해도 괜찮을 것 같습니다.
dynamic으로 받게되었을 때 사용하시는 분들이 헷갈리실거같다면
Freezed를 이용한 유니온 파라미터 클래스를 하나 만들어도 괜찮을 것 같아요.

**Comment by viiviii** [comment]
JP님과 슬랙에서 여러 대화를 나눈 끝에 아래와 같이 결정했으므로 이 이슈를 닫도록 하겠습니다.

> 📌
> String으로 받고 List<String> 필요 시 사용자가 플랫해서 쓰도록 한다.
