### ISSUE TITLE
Effective Dart에 맞게 상수 명명 방식 수정

### ISSUE THREAD

**Issue by jpoh281** [jpoh281/flutter_korea_regexp#20]
# Effective Dart에 맞게 상수 명명 방식 수정

https://dart.dev/guides/language/effective-dart/style

위의 주소로 들어가서 아래 스크린샷에 해당하는 부분을 보면 상수에 헝가리 표기법으로 k를 붙이지 않는 것을 추천하며, 또한 그냥 lowerCamelCase를 사용하기를 추천하고 있습니다.

이때까지 Flutter 팀의 위젯을 보고.. k를 붙여서 사용했었는데 배신감이....
기존 언어와의 통일성?등을 이유로  SCREAMING_CAPS 를 사용해도 되기는 하지만,  

- SCRIMING_CAPS는 많은 경우, 특히 CSS 색상 등의 열거값이 불량해 보입니다.
- 상수는 종종 최종 비상수 변수로 변경되는데, 이는 이름을 변경해야 합니다.
- 열거형에서 자동으로 정의되는 값 속성은 const 및 소문자입니다.

위와 같은 이유로 lowerCamelCase를 사용한다고 합니다.

![image](https://user-images.githubusercontent.com/54665433/159694191-78cef4cc-3d41-4037-a0e0-a4c8376c2821.png)
![image](https://user-images.githubusercontent.com/54665433/159694280-99ff3bdc-2929-4be5-b1d3-74cf7d6b8930.png)

@viiviii 님 현재 constant에 있는 상수들을 lowerCamelCase로 변경하려고 하는데 어떻게 생각하시나요?

**Comment by viiviii** [comment]
후.. 저도 k붙여서 썼었는데ㅋㅋㅋㅋㅋ정말 좋습니다! 다트는 상수를 소문자로 해줘야 제 맛이죠👍 👍

![image](https://user-images.githubusercontent.com/75404713/159704805-3e398c77-1047-418b-a3f9-268fadd478e0.png)
