### ISSUE TITLE
복합 모음으로 합칠 수 있는지 체크하는 조건을 개선

### ISSUE THREAD

**Issue by viiviii** [jpoh281/flutter_korea_regexp#23]
안녕하세요! 

현재 복합 모음을 합치는 로직(ex: `ㅗㅏ -> ㅘ`)은 아래와 같이 조건 체크 후 합치고 있습니다.
1. 이전 값과 현재 값이 모음(중성)인지 확인 - `isMedial`
2. 복합 모음으로 합칠 수 있는지 확인 - `mixedMedial != null`

https://github.com/jpoh281/flutter_korea_regexp/blob/d1bed1dd01f4ce13313df9a9863b9b58a502f1f5/lib/src/implode.dart#L27-L28

제가 생각하는 이유는 다음과 같아요!
- 해당 로직에선 중성(모음)만 합쳐야하기 때문에 이전 값과 현재 값이 중성(모음)인지 확인
  -  ([MIXED](https://github.com/jpoh281/flutter_korea_regexp/blob/d1bed1dd01f4ce13313df9a9863b9b58a502f1f5/lib/src/constant.dart#L88-L109) 상수에 중성, 종성이 하나로 합쳐져 있으므로)

그래서 아래와 같이 바꾸면 어떨까합니다.
- 현재 하나의 MIXED를 좀 더 세분화 (ex: `MEDIAL_MIXED`, `FINALE_MIXED`)
- 이전 값과 현재 값이 모음인지 확인하지 않고 `MEDIAL_MIXED`를 바로 사용

### 예상 변경 코드
- constant.dart [MIXED](https://github.com/jpoh281/flutter_korea_regexp/blob/d1bed1dd01f4ce13313df9a9863b9b58a502f1f5/lib/src/constant.dart#L88-L109)
```dart
const Map<String, List<String>> MIXED = {
  ...MEDIAL_MIXED,
  ...FINALE_MIXED,
};

const Map<String, List<String>> MEDIAL_MIXED = { //생략 }
const Map<String, List<String>> FINALE_MIXED = { //생략 }
```

- implode.dart [mixMedial()](https://github.com/jpoh281/flutter_korea_regexp/blob/d1bed1dd01f4ce13313df9a9863b9b58a502f1f5/lib/src/implode.dart#L27-L28)
```dart
// if (_isMedial(previous) && _isMedial(current) && mixedMedial != null) { -- 제거
if (mixedMedial != null) {
```

### 장점
- 이 작업을 해도 동작에는 변경이 없을 걸로 예상됨
- 기존 MIXED 상수의 구성을 좀 더 파악하기 쉬워짐
- 조건이 단순해짐: `이전 값 모음 체크 + 현재 값 모음 체크 + 복합 자모 체크` => `복합 모음 체크`

다양한 의견 부탁드립니다🤗

**Comment by jpoh281** [comment]
- 자소 분해하기 [https://github.com/jpoh281/flutter_korea_regexp/blob/master/lib/src/explode.dart](url)
https://github.com/jpoh281/flutter_korea_regexp/blob/0cc278c79f2fafb1e06f9013fd48e9568e6e517c/lib/src/explode.dart#L10-L24

자소 분해하기의 경우 mixed에 중성(모음)을 대입해서 있는지 확인, 종성(받침)을 대입해서 있는지 확인하기때문에
부가적인 영향을 받지 않을 것으로 보입니다.

- 자동완성 기능 [https://github.com/jpoh281/flutter_korea_regexp/blob/master/lib/src/get_regexp.dart](url)
https://github.com/jpoh281/flutter_korea_regexp/blob/0cc278c79f2fafb1e06f9013fd48e9568e6e517c/lib/src/get_regexp.dart#L41-L44

자동완성 기능에서도 종성을 분해해서 다음 글자의 초성으로 예) 읽 -> 읽[가-힣]  || 일[가-힣]으로 분해해서 사용하기때문에
영향을 받지 않을 것으로 보입니다.

말씀하신 방식대로 변경해도 문제 없을 것이라고 생각되요.
