### ISSUE TITLE
텍스트 필드에 empty string을 넣었을때, 에러가 발생합니다.

### ISSUE THREAD

**Issue by BottlePumpkin** [jpoh281/flutter_korea_regexp#34]
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.1, on macOS 13.5.2 22G91 darwin-arm64, locale ko-KR)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.5/libexec/bin/dart, which is not inside your current
      Flutter SDK checkout at /Users/lulu/dev/flutter. Consider adding /Users/lulu/dev/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

버전: korea_regexp: 1.0.1

텍스트필드에 값을 입력하고, 지우는 과정에서 empty string이 되었을때 아래와 같은 에러가 발생 합니다.
`Invalid value: Valid value range is empty: -1`

**Comment by jpoh281** [comment]
이슈 처리 완료되어 닫겠습니다.
